	LJMP INIT
	
	ORG 01BH
	RETI
	;LJMP TIN1
	
	ORG 023H
	LJMP UART

	ORG 50H
INIT:
	MOV R6,#0
	MOV R7,#64H
	
	MOV SCON,#01010000B
	
	MOV TH1,#0FDH
	MOV TL1,#0FDH
	MOV TMOD,#00100000B
	MOV TCON,#01000000B
	MOV IE, #0H
	;SETB ET1
	SETB ES
	SETB EA
	LJMP MAIN
	
	ORG 100H
MAIN:
	INC R6
	LJMP MAIN
	

	ORG 200H	
TIN1:
	RETI
		
UART:
	MOV B, SBUF
	ANL A, #11011111B
	MOV 50H, A 	; Pod adresem 50H w internal RAM znajdzie sie kod nacisnietego znaku
	MOV SBUF, A
	CLR TI
	CLR RI
	RETI

WES_SW:
	MOV SBUF, #2AH; *
	MOV SBUF, #2AH; *
	MOV SBUF, #2AH; *
	MOV SBUF, #2AH; *
	MOV SBUF, #2AH; *
	MOV SBUF, #57H; W
	MOV SBUF, #45H; E
	MOV SBUF, #53H; S
	MOV SBUF, #4FH; O
	MOV SBUF, #4CH; L
	MOV SBUF, #59H; Y
	MOV SBUF, #43H; C
	MOV SBUF, #48H; H
	MOV SBUF, #20H; 
	MOV SBUF, #20H;  
	MOV SBUF, #53H; S
	MOV SBUF, #57H; W
	MOV SBUF, #49H; I
	MOV SBUF, #41H; A
	MOV SBUF, #54H; T
	MOV SBUF, #2AH; *
	MOV SBUF, #2AH; *
	MOV SBUF, #2AH; *
	MOV SBUF, #2AH; *
	MOV SBUF, #0DH; CR
	MOV SBUF, #0AH; LF (nowa linia)
	MOV SBUF, #2AH; *
	RET
END